version: "3.9"

services:
  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - ./backend:/app
    command: composer install --no-interaction

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # Asegura variables en contenedor (también están en .env)
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    command: bash -lc "php artisan migrate --seed && php artisan serve --host 0.0.0.0 --port 8000"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: bash -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
