name: CI Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, sqlite3, pdo_sqlite, dom, xml, ctype, json, openssl, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --ansi

      - name: Prepare environment
        run: |
          if [ -f .env.testing ]; then cp .env.testing .env; else cp .env.example .env; fi
          php artisan key:generate
          mkdir -p database
          touch database/database.sqlite

      - name: Migrate & Seed
        run: php artisan migrate --seed --no-interaction

      - name: Run tests
        run: php artisan test --no-interaction
