name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          extensions: sqlite
          tools: composer

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env.testing
        run: |
          cat > .env.testing <<'EOF'
          APP_ENV=testing
          APP_DEBUG=true
          APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          DB_CONNECTION=sqlite
          DB_DATABASE=:memory:
          API_KEY=ci_dummy_key_123
          API_RATE_LIMIT=60
          API_CACHE_TTL=1
          EOF

      - name: Lint (Pint)
        run: composer lint

      - name: Static analysis (PHPStan)
        run: composer phpstan

      - name: Tests (PHPUnit + coverage)
        run: |
          php artisan test --coverage-clover=coverage.xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test (+ coverage)
        run: npm test -- --coverage --watch=false

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
