name: Frontend CI

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: frontend
        run: npm ci
      - name: Lint
        working-directory: frontend
        run: npm run lint
      - name: Test
        working-directory: frontend
        run: npm test -- --watch=false
      - name: Build
        working-directory: frontend
        env:
          VITE_API_BASE_URL: http://127.0.0.1:8000/api
          VITE_API_KEY: dummy_ci_key 
        run: npm run build
