name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, sqlite, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare sqlite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Copy env testing
        run: cp .env.testing .env

      - name: Generate key
        run: php artisan key:generate

      - name: Migrate
        run: php artisan migrate --force

      - name: Lint (Pint)
        run: composer lint

      - name: PHPStan
        run: composer phpstan

      - name: Tests
        run: composer test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        env:
          VITE_API_BASE_URL: http://localhost
          VITE_API_KEY: sk_ci_dummy
        run: npm test -- --watch=false
